// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY4Q5FTybQnrQvTeltcUv5kf5ECdL8PLU',
    appId: '1:181292718652:web:1872f235086abb698b0139',
    messagingSenderId: '181292718652',
    projectId: 'sulmtak',
    authDomain: 'sulmtak.firebaseapp.com',
    databaseURL: 'https://sulmtak-default-rtdb.firebaseio.com',
    storageBucket: 'sulmtak.firebasestorage.app',
    measurementId: 'G-7JEW6ZDXJG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADmYW51_bD-Wg-nvg8xWT5LGETUL3rouo',
    appId: '1:181292718652:android:4391da0d30e02b3d8b0139',
    messagingSenderId: '181292718652',
    projectId: 'sulmtak',
    databaseURL: 'https://sulmtak-default-rtdb.firebaseio.com',
    storageBucket: 'sulmtak.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgDv1wjCGdQK8iuugP8xgnY70pPyOUV8M',
    appId: '1:181292718652:ios:fde52e5cad9989ce8b0139',
    messagingSenderId: '181292718652',
    projectId: 'sulmtak',
    databaseURL: 'https://sulmtak-default-rtdb.firebaseio.com',
    storageBucket: 'sulmtak.firebasestorage.app',
    iosBundleId: 'com.app.salmtakDoctorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgDv1wjCGdQK8iuugP8xgnY70pPyOUV8M',
    appId: '1:181292718652:ios:fde52e5cad9989ce8b0139',
    messagingSenderId: '181292718652',
    projectId: 'sulmtak',
    databaseURL: 'https://sulmtak-default-rtdb.firebaseio.com',
    storageBucket: 'sulmtak.firebasestorage.app',
    iosBundleId: 'com.app.salmtakDoctorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQPJUTYJ3m9vp-Gl2-OL7UL1FWfvaunKA',
    appId: '1:181292718652:web:38b79163b3d302b78b0139',
    messagingSenderId: '181292718652',
    projectId: 'sulmtak',
    authDomain: 'sulmtak.firebaseapp.com',
    databaseURL: 'https://sulmtak-default-rtdb.firebaseio.com',
    storageBucket: 'sulmtak.firebasestorage.app',
    measurementId: 'G-CB6NTE1W2K',
  );

}